### ISSUE TITLE
Why not set the scale factor to 1 or 0.08?

### ISSUE THREAD

**Issue by zhouhang95** [matunnkazumi/blender2pmxem#70]
set 1 to match scale in pe/mmd
set 0.08 to match scale in real world

**Comment by matunnkazumi** [comment]
Sorry. I don't know.

I'm not original authors. I'm just migrating to Blender 2.80.

Many people and I use older version.
I can't change the specification.

**Comment by zhouhang95** [comment]
Could you to add function set scale when import model?
